from typing import Protocol

class Clickable(Protocol):
    def on_hover_enter(self) -> None: ...
    def on_hover_exit(self) -> None: ...
    def click(self) -> None: ...
    
class Deck(Protocol):
    def used(self, n: int) -> None: ...
    def render(self, screen) -> None: ...
    def draw(self, amount) -> None: ...
    
class Card(Protocol):
    def use(self, target) -> None: ...